routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin', function () {
    return view('layouts/admin');
});

Route::get('/prueba', function () {
    return view('prueba');
});
//reportes
Route::get('sales/reports_day','ReportController@reports_days')->name('reports.day');
Route::get('sales/ reports_date', 'ReportController@reports_date')->name('reports.date');
Route::post('sales/report_results', 'ReportController@report_results')->name('report.results');


Route::get('search/productos','ProductController@search')->name('search.productos');

Route::resource('categories','CategoryController')->names('categories');
Route::resource('clients','ClientController')->names('clients');
Route::resource('products','ProductController')->names('products');
Route::resource('providers','ProviderController')->names('providers');
Route::resource('purchases','PurchaseController')->names('purchases');
Route::resource('sales' ,'SaleController')->names('sales');

Route::get('purchases/pdf/{purchase}', 'PurchaseController@pdf')->name('purchases.pdf');
Route::get('sales/pdf/{sale}', 'SaleController@pdf')->name('sales.pdf');
Route::get('productos/pdf', 'ProductController@pdf')->name('products.pdf');

Route::get('purchases/upload/{purchase}', 'PurchaseController@upload')->name('upload.purchases');


Route::get('change_status/products/{product}', 'ProductController@change_status')->name('change.status.products'); 
Route::get('change_status/purchases/{purchase}', 'PurchaseController@change_status')->name('change.status.purchases');
Route::get('change_status/sales/{sale}', 'SaleController@change_status')->name('change.status.sales');

Route::resource('user' ,'UserController')->names('users');
Route::resource('roles' ,'RoleController')->names('roles');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
    'code',
    'name',
    'price',
    'stock',
    'image',
    'status',
    'category_id',
    'provider_id',
    ];
    
    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function provider(){
        return $this->belongsTo(Provider::class);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Product;
use App\Provider;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Request\Product\StoreRequest;
use App\Http\Request\Product\UpdateRequest;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Barryvdh\DomPDF\Facade\Pdf; 

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:products.create')->only(['create','store']);
        $this->middleware('can:products.index')->only(['index']);
        $this->middleware('can:products.edit')->only(['edit','update']);
        $this->middleware('can:products.show')->only(['show']);
        $this->middleware('can:products.destroy')->only(['destroy']);
        $this->middleware('can:change.status.products')->only(['change_status']);
        $this->middleware('can:products.pdf')->only(['pdf']);
        

    }

    public function index()
    {
         $products = Product::orderBy('provider_id','asc')->orderBy('category_id','asc')->orderBy('name','asc')->paginate(100);
        return view('admin.product.index',compact('products'));
    }

  
    public function create()
    {
        $categories = Category::orderBy('name','asc')->get();
        $providers = Provider::get();
        return view('admin.product.create',compact('categories','providers'));
    }


    public function store(StoreRequest $request)
    {
        if ($request -> hasFile('picture')) {
            $file = $request -> file('picture');
            $image_name = time().'_'.$file->getClientOriginalName();
            $file->move(public_path("/image"),$image_name);
            
            $product = Product::create($request->all()+[
                'image'=>$image_name,
            ]);
        }else{
            $product = Product::create($request->all());
        }


        $product->update(['code'=>$product->id]);
        return redirect()->route('products.index');
    }

  
    public function show(Product $product)
    {
        return view('admin.product.show',compact('product'));
    }


    public function edit(Product $product)
    {
        $categories = Category::get();
        $providers = Provider::get();
        return view('admin.product.edit',compact('product','categories','providers'));
    }

  
    public function update(UpdateRequest $request, Product $product)
    {
        if ($request -> hasFile('picture')) {
            $file = $request -> file('picture');
            $image_name = time().'_'.$file->getClientOriginalName();
            $file->move(public_path("/image"),$image_name);
         
            $product->update($request->all()+[
                'image'=>$image_name,
            ]);
        }
        $product->update($request->all());

        return redirect()->route('products.index');
    }

  
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index');
    }    

    public function change_status(Product $product)
    {
        if ($product->status == 'ACTIVO') {
            $product->update(['status'=>'INACTIVO']);
            return redirect()->back();
        } else {
            $product->update(['status'=>'ACTIVO']);
            return redirect()->back();
        } 
    }

    public function search(Request $request){
        $term = $request->get('term');

        $querys =  Product::where('name','LIKE','%'. $term . '%')->get();

        $data = [];
        $nombre;
        $stock;
        
        foreach($querys as $query){
            $data[] = [
                'label' => $query->code.", ".$query->category->name. ",  " .$query->name. ",  Existencias = " .$query->stock. ",  Precio = ".$query->price
    
            ];
        }
        return $data;
    }

    public function pdf()
    {  
        $products = Product::orderBy('provider_id','asc')->orderBy('category_id','asc')->orderBy('name','asc')->get();
        $date = Carbon::now('america/Guatemala');
        $pdf = PDF::loadView('admin.product.pdf', compact('products','date'));
        return $pdf->download('Reporte_de_inventario_.pdf');

    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.admin')

@section('title','Registrar Producto')
@section('styles')

{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Registro de Productos
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">

                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item"><a href="{{route('products.index')}}">Productos</a></li>
                <li class="breadcrumb-item active" aria-current="page">registro de Productos</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title">Registro de productos</h4>          
                    </div>
                    {!! Form::open(['route'=>'products.store','method'=>'POST','files' => true]) !!}
                    <div class="form-group">
                        <label for="names">Nombre Producto</label>
                        <input type="text"  class="form-control" name="name" id="name" 
                                placeholder="Nombre" aria-describedby="helpId" required>
                    </div>
                    <div class="form-group">
                        <label for="prices">Precio </label>
                        <input type="number" class="form-control" name="price" id="price" 
                                placeholder="precio" aria-describedby="helpId" required>
                    </div>
                    <div class="form-group">
                        <label for="category_ids">Categoria</label>
                        <select class="form-control" name="category_id" id="category_id">
                        <option value="">Seleccione Categoria</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="provider_ids">Proveedor</label>
                        <select class="form-control" name="provider_id" id="provider_id">
                        <option value="">Seleccione Proveedor</option>
                            @foreach($providers as $provider)
                                <option value="{{$provider->id}}">{{$provider->name}} ({{$provider->empresa}}) </option>
                            @endforeach
                        </select>
                    </div>
                    <!-- <div class="custom-file mb-4">
                        <input type="file" name="picture" id="picture" class="custom-file-input" lang="es">
                        <label for="" class="custom-file-label" for="images">Cargar Imagen de Producto</label>
                    </div> -->
                    <div class="card-body">
                        <h4 class="card-title d-flex">Imagen de producto (opcional)
                            <small class="ml-auto align-self-end">
                                <a href="#" class="font-weight-light" 
                                target="_blank"></a>
                            </small>
                        </h4>
                        <input type="file" name="picture" id="picture" class="dropify">
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Registrar</button>
                    <a href="{{route('products.index')}}" class="btn btn-light">Cancelar</a>
                    {!! Form::close() !!}
                </div>
               {{--
                <div class="card-footer text-muted">
                    {{$products->render()}}
                </div>
                --}}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
{{!! Html::script('melody/js/dropify.js') !!}}
{!! Html::script('treegrid/js/jquery.treegrid.js') !!}
{!! Html::script('js/my_functions.js') !!}
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree').treegrid().treegrid('collapseAll');
    });
</script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.admin')

@section('title','Editar Producto')
@section('styles')

{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Editar Productos
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">

                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item"><a href="{{route('products.index')}}">Productos</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edicion de Producto</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title">Registro de productos</h4>          
                    </div>
                    {!! Form::open(['route'=>['products.update',$product],'method'=>'PUT','files' => true]) !!}
                    <div class="form-group">
                        <label for="names">Nombre Producto</label>
                        <input type="text"  class="form-control" name="name" id="name" value="{{$product->name}}"
                                placeholder="Nombre" aria-describedby="helpId" required>
                    </div>
                    <div class="form-group">
                        <label for="prices">Precio </label>
                        <input type="number" class="form-control" name="price" id="price" value="{{$product->price}}"
                                placeholder="precio" aria-describedby="helpId" required>
                    </div>
                    <div class="form-group">
                        <label for="category_ids">Categoria</label>
                        <select class="form-control" name="category_id" id="category_id">
                        <option value="">Seleccione Categoria</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}"
                                @if($category->id ==$product->category_id)
                                selected
                                @endif
                                > {{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="provider_ids">Proveedor</label>
                        <select class="form-control" name="provider_id" id="provider_id">
                        <option value="">Seleccione Proveedor</option>
                            @foreach($providers as $provider)
                                <option value="{{$provider->id}}" 
                                @if($provider->id==$product->provider_id)
                                selected
                                @endif
                                >{{$provider->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <!-- <div class="custom-file mb-4">
                        <input type="file" name="image" id="image" class="custom-file-input" lang="es">
                        <label for="" class="custom-file-label" for="images">Cargar Imagen de Producto</label>
                    </div> -->

                    <div class="card-body">
                        <h4 class="card-title d-flex">Imagen de producto
                            <small class="ml-auto align-self-end">
                                <a href="#" class="font-weight-light" 
                                target="_blank"></a>
                            </small>
                        </h4>
                        <input type="file" name="picture" id="picture" class="dropify">
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Actualizar</button>
                    <a href="{{route('products.index')}}" class="btn btn-light">Cancelar</a>
                    {!! Form::close() !!}
                </div>
               {{--
                <div class="card-footer text-muted">
                    {{$products->render()}}
                </div>
                --}}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
{{!! Html::script('melody/js/dropify.js') !!}}
{!! Html::script('treegrid/js/jquery.treegrid.js') !!}
{!! Html::script('js/my_functions.js') !!}
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree').treegrid().treegrid('collapseAll');
    });
</script>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin')

@section('title','Gestión de Productos')
@section('styles')
<style type="text/css">
    .unstyled-button{
        border: none;
        padding: 0;
        background: none; 
    }
</style>
{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Productos
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">
                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item active" aria-current="page">Productos</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title"></h4>
                        <div class="btn-group">
                            <a href="{{route('products.create')}}" type="button" class="btn btn-info ">
                                <i class="fas fa-plus"></i> Nuevo
                            </a>
                            <hr><hr><hr><hr>
                            <a href="{{route('products.pdf')}}" class="btn btn-outline-danger" title="Generar PDF" style="width: 20%;">
                                <i class="far fa-file-pdf"></i></a>
                        </div>
                    </div>
                       
                    <div class="table-responsive">
                        <table id="category_listing" class="table tree">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nombre</th>
                                    <th>Precio</th>
                                    <th>Stock</th>         
                                    <th>Estado</th>        
                                    <th>Categoria</th>    
                                    <th>Proveedor</th>      
                                    <th>Acciones</th>       
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach ($products as $product)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td>
                                        <a href="{{route('products.show',$product)}}">{{$product->name}}</a>
                                    </td> 
                                    <td>{{$product->price}}</td>
                                    <td>{{$product->stock}}</td>
                                    @if($product->status == 'ACTIVO')
                                    <td> <a href="{{route('change.status.products',$product)}}" title="Editar" class="jsgrid-button btn btn-success">
                                        Activo <i class="fas fa-check"></i>
                                    </a>
                                    </td>
                                    @else
                                    <td> <a href="{{route('change.status.products',$product)}}" title="Editar" class="jsgrid-button btn btn-danger">
                                        Inactivo <i class="fas fa-times"></i>
                                    </a>
                                    </td>
                                    @endif
                                    <td>{{$product->category->name}}</td>
                                    <td>{{$product->provider->empresa}}</td>
                                    <td style="width: 75px">
                                        {!! Form::open(['route'=>['products.destroy',
                                            $product ], 'method'=>'DELETE']) !!}

                                        <a class="jsgrid-button jsgrid-edit-button" href="{{route('products.edit',$product)}}" title="Editar">
                                            <i class="far fa-edit"></i>
                                        </a>
                                       <button class="jsgrid-button jsgrid-delete-button unstyled-button" type="submit" title="Eliminar">
                                        <i class="far fa-trash-alt"></i>
                                        </button> 
                                       {!! Form::close() !!}
                                    </td>
                                    
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                </div>
                
             <div class="card-footer text-muted">
                 {{$products->render()}}
           </div>

            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

{!! Html::script('treegrid/js/jquery.treegrid.js') !!}
{!! Html::script('js/my_functions.js') !!}
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree').treegrid().treegrid('collapseAll');
    });
</script>
@endsection

resources/views/admin/product/show.blade.php
@extends('layouts.admin')
@section('title','información del Producto')
@section('styles')

@endsection
@section('create')

@endsection
@section('options')

@endsection
@section('preference')

@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            {{$product->name}}
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">
                <li class="breadcrumb-item"><a href="#">Panel administrador</a></li> 
                <li class="breadcrumb-item"><a href="{{route('products.index')}}">Productos</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{$product->name}}</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="border-bottom text-center pb-4">
                            <img src="{{asset('image/'.$product->image)}}" alt="profile"
                                             class="img-lg mb-3">

                                <h3>{{$product->name}}</h3>
                                <div class="d-flex justify-content-between">
                                </div>
                            </div>
        
    
                            <div class="border-bottom py-4">
                                <div class="list-group">
                                    <button type="button" class="list-group-item list-group-item-action">Info Categoria</button>

                                   <a href="{{route('providers.show',$product->provider->id)}}">
                                    <button type="button" class="list-group-item list-group-item-action">
                                        Info. proveedor</button></a>
                                </div>
                            </div>
                            @if($product->status =='ACTIVE')
                            <button class="btn btn-success btn-block">{{$product->status}}</button>
                            @else
                            <button class="btn btn-success btn-block">{{$product->status}}</button>
                            @endif
                        </div>
                        <div class="col-lg-8 pl-lg-5">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <h4>Información de proveedor</h4>
                                </div>
                            </div>
                            <div class="profile-feed">
                                <div class="d-flex align-items-start profile-feed-item">

                                   

                                    <div class="form-group col-md-6">
                                        <strong><i class="fas fa-address-card mr-1"></i> Codigo</strong>
                                        <p class="text-muted">
                                            {{$product->code}}
                                        </p>
                                        <hr>
                                        <strong><i class="fab fa-product-hunt mr-1"></i> Nombre</strong>
                                        <p class="text-muted">
                                            {{$product->name}}
                                        </p>
                                        <hr>
                                        <strong><i class="fas fa-address-card mr-1"></i> Precio</strong>
                                        <p class="text-muted">
                                            {{$product->price}}
                                        </p>
                                        <hr>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <strong>
                                            <i class="fas fa-address-card mr-1"></i>
                                            Estado</strong>
                                        <p class="text-muted">
                                            {{$product->status}}
                                        </p>
                                        <hr>
                                        <strong><i class="fas fa-envelope mr-1"></i> Categoria</strong>
                                        <p class="text-muted">
                                            {{$product->category->name}}
                                        </p>
                                        <hr>
                                        <strong><i class="fas fa-envelope mr-1"></i>Proveedor</strong>
                                        <p class="text-muted">
                                            {{$product->provider->name}}
                                        </p>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    <a href="{{route('products.index')}}" class="btn btn-primary float-right">Regresar</a>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection
@section('scripts')
{!! Html::script('melody/js/profile-demo.js') !!}
{!! Html::script('melody/js/data-table.js') !!}
@endsection