routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin', function () {
    return view('layouts/admin');
});

Route::get('/prueba', function () {
    return view('prueba');
});
//reportes
Route::get('sales/reports_day','ReportController@reports_days')->name('reports.day');
Route::get('sales/ reports_date', 'ReportController@reports_date')->name('reports.date');
Route::post('sales/report_results', 'ReportController@report_results')->name('report.results');


Route::get('search/productos','ProductController@search')->name('search.productos');

Route::resource('categories','CategoryController')->names('categories');
Route::resource('clients','ClientController')->names('clients');
Route::resource('products','ProductController')->names('products');
Route::resource('providers','ProviderController')->names('providers');
Route::resource('purchases','PurchaseController')->names('purchases');
Route::resource('sales' ,'SaleController')->names('sales');

Route::get('purchases/pdf/{purchase}', 'PurchaseController@pdf')->name('purchases.pdf');
Route::get('sales/pdf/{sale}', 'SaleController@pdf')->name('sales.pdf');
Route::get('productos/pdf', 'ProductController@pdf')->name('products.pdf');

Route::get('purchases/upload/{purchase}', 'PurchaseController@upload')->name('upload.purchases');


Route::get('change_status/products/{product}', 'ProductController@change_status')->name('change.status.products'); 
Route::get('change_status/purchases/{purchase}', 'PurchaseController@change_status')->name('change.status.purchases');
Route::get('change_status/sales/{sale}', 'SaleController@change_status')->name('change.status.sales');

Route::resource('user' ,'UserController')->names('users');
Route::resource('roles' ,'RoleController')->names('roles');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    protected $fillable = [
        'provider_id',
        'user_id',
        'purchase_date',
        'description',
        'total',
        'status',
        'picture',
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }
    public function provider(){
        return $this->belongsTo(Provider::class);
    }
    public function purchaseDetails(){
        return $this->hasMany(PurchaseDetails::class);
    }
    public function update_stock($id, $quantity){
        $product = Product::find($id);
        $product->add_stock($quantity);
    }
    public function my_store($request){
        $purchase = self::create($request->all()+[
            'user_id'=>Auth::user()->id,
            'purchase_date'=>Carbon::now('america/Guatemala'),
        ]);
        $purchase->add_purchase_details($request);
    }
    public function add_purchase_details($request){
        foreach ($request->product_id as $key => $id) {
            $this->update_stock($request->product_id[$key], $request->quantity[$key]);
            $results[] = array("product_id"=>$request->product_id[$key], "quantity"=>$request->quantity[$key], "price"=>$request->price[$key]);
        }
        $this->purchaseDetails()->createMany($results);
    }
}

app/Http/Controllers/PurchaseController.php
<?php
namespace App\Http\Controllers;
use App\Purchase;
use App\Provider;
use App\Product;
use App\PurchaseDetails;
use Illuminate\Http\Request;
use App\Http\Request\Purchase\StoreRequest;
use App\Http\Request\Purchase\UpdateRequest;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Barryvdh\DomPDF\Facade\Pdf; 
class PurchaseController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:purchases.create')->only(['create','store']);
        $this->middleware('can:purchases.index')->only(['index']);
        $this->middleware('can:purchases.show')->only(['show']);
        
        $this->middleware('can:change.status.purchases')->only(['change_status']);
        $this->middleware('can:purchases.pdf')->only(['pdf']);
        $this->middleware('can:upload.purchases')->only(['upload']);

    }


    public function index()
    {
        $purchases = Purchase::paginate(5);
        return view('admin.purchase.index', compact('purchases'));
    }
    public function create()
    {
        $providers = Provider::get();

        $products = Product::orderBy('category_id','asc')->orderBy('name','asc')->where('status','ACTIVO')->get();

        return view('admin.purchase.create', compact('providers','products'));
    }
    public function store(StoreRequest $request,Purchase $purchase)//Purchase $purchase
    {
        //dd($request);
        $purchase = Purchase:: create($request->all()+[
        'user_id' => Auth::user()->id,
        'purchase_date' =>Carbon::now('america/Guatemala'),
        ]);
    //    $purchase->my_store($request);
        
        foreach($request->product_id as $key=>$product){
           $results[] = array("product_id"=>$request->product_id[$key],
           "quantity"=>$request->quantity[$key], "price"=>$request->price[$key]);
        }
        $purchase->purchaseDetails()->createMany($results);
        //->with('toast_success', '¡Compra registrada con éxito!')
        return redirect()->route('purchases.index');
    }

    public function show(Purchase $purchase)
    {
        $subtotal = 0 ;
        $purchaseDetails = $purchase->purchaseDetails;
        foreach ($purchaseDetails as $purchaseDetail) {
            $subtotal += $purchaseDetail->quantity * $purchaseDetail->price;
        }
      
        return view('admin.purchase.show', compact('purchase', 'purchaseDetails', 'subtotal'));
    }
    public function edit(Purchase $purchase)
    {
        // $providers = Provider::get();
        // return view('admin.purchase.edit', compact('purchase'));
    }
    public function update(UpdateRequest $request, Purchase $purchase)
    {
        // $purchase->update($request->all());
        // return redirect()->route('purchases.index');
    }
    public function destroy(Purchase $purchase)
    {
        // $purchase->delete();
        // return redirect()->route('purchases.index');
    }

    public function pdf(Purchase $purchase)
    {
        $subtotal = 0 ;
        $purchaseDetails = $purchase->purchaseDetails;
        foreach ($purchaseDetails as $purchaseDetail) {
            $subtotal += $purchaseDetail->quantity * $purchaseDetail->price;
        }
        $pdf = PDF::loadView('admin.purchase.pdf', compact('purchase', 'subtotal', 'purchaseDetails'));
        return $pdf->download('Reporte_de_compra_'.$purchase->id.'.pdf');
    }
    
    public function upload(Request $reques, Purchase $purchase)
    {
        // $purchase->update($request->all());
        // return redirect()->route('purchases.index');
    }

    public function change_status(Purchase $purchase)
    {
        if ($purchase->status == 'VALID') {
            $purchase->update(['status'=>'CANCELED']);
            return redirect()->back();
        } else {
            $purchase->update(['status'=>'VALID']);
            return redirect()->back();
        } 
    }
}

resources/views/admin/purchase/_form.blade.php
<div class="form-group">
     <label for="provider_ids">Proveedor</label>
    <select class="form-control" name="provider_id" id="provider_id">
        <option value="">Proveedor</option>
        @foreach($providers as $provider)
        <option value="{{$provider->id}}">{{$provider->name}} ({{$provider->empresa}})</option>
        @endforeach
    </select>
</div>
<div class="form-group">
    <label for="descriptions">Descripcion de compra</label>
    <input type="text"  class="form-control" name="description" id="description" 
        placeholder="Nombre" aria-describedby="helpId" >
</div>
 <div class="form-group">
     <label for="product_ids">Productos</label>
    <select class="form-control" name="product_id" id="product_id">
        <option value="">Seleccione Produto</option>
        @foreach($products as $product)
        <option value="{{$product->id}}">prd- {{$product->category->name}} {{$product->name}}</option>
        @endforeach
    </select>
</div>
<!-- input de Search -->
<!-- <div class="form-group">
     <label for="product_search">Buscar Productos</label>
     <input type="text"  class="form-control" name="search" id="search" 
        placeholder="escriba el nombre" aria-describedby="helpId" > <br><br><br><br>
</div> -->

<div class="form-group">
    <label for="quantities">Cantidad Comprada</label>
    <input type="number"  class="form-control" name="quantity" id="quantity" 
        placeholder="cantidad" aria-describedby="helpId" >
</div>
<div class="form-group">
    <label for="prices">Precio de Compra</label>
    <input type="number"  class="form-control" name="price" id="price" 
        placeholder="precio" aria-describedby="helpId" >
</div>

<div class="form-group">
    <button type="button" id="agregar" class="btn btn-primary float-right">Agregar Producto</button>
</div>

<div class="form-group">
    <h4 class="card-title">Detalles de Compra</h4>
    <div class="table-responsive col.md-12">
         <table id="detalles" class="table table-striped">
            <thead>
                <tr>
                    <th>Eliminar</th>
                    <th>Producto</th>
                    <th>Precio (Q)</th>
                    <th>Cantidad</th>
                    <th>Sub-total (Q)</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th colspan="4">
                        <p align="right" >TOTAL: </p>
                    </th>
                    <th>
                        <p align="right" ><span id="total">Q. 0.00</span></p>
                    </th>
                </tr>
                <tr id="dvOcultar">
                <th colspan="4">
                        <p align="right" >Total a pagar: </p>
                    </th>
                    <th>
                        <p align="right" ><span id="total_pagar_html">Q. 0.00</span>
                            <input type="hidden" name="total" id="total_pagar">
                        </p>
                    </th>
                </tr>
            </tfoot>
        </table>   
    </div>
</div>

resources/views/admin/purchase/create.blade.php
@extends('layouts.admin')

@section('title','Registro de Compras')
@section('styles')
<link rel="stylesheet" href="{{asset('jquery-ui/jquery-ui.min.css')}}">
{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Registro de Compras
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">

                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item"><a href="{{route('purchases.index')}}">Compras</a></li>
                <li class="breadcrumb-item active" aria-current="page">registro de Compras</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
            {!! Form::open(['route'=>'purchases.store','method'=>'POST']) !!}
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title">Registro de compras</h4>          
                    </div>
                    
                    @include('admin.purchase._form')                 

                </div>    
                <div class="card-footer text-muted">
                <button type="submit" id="guardar" class="btn btn-primary float-right">Registrar</button>
                    <a href="{{route('purchases.index')}}" class="btn btn-light">Cancelar</a>
                </div>
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script src="{{asset('jquery-ui/jquery-ui.min.js')}}" ></script>
<script>
  
    $('#search').autocomplete({
        source: function(request, response){
            $.ajax({
                url: "{{route('search.productos')}}",
                dataType: 'json',
                data: {
                    term: request.term
                },
                success: function(data){
                    response(data)
                    console.log(data)
                }

            });
        }
    });

</script>
{!! Html::script('melody/js/alerts.js') !!}
{!! Html::script('melody/js/avgrund.js') !!}

{!! Html::script('melody/js/bootstrap-select.min.js') !!}
{!! Html::script('melody/js/sweetalert2.all.min.js') !!}

{!! Html::script('melody/js/jquery.treegrid.js') !!}
{!! Html::script('melody/js/my_functions.js') !!}

<script>
    $(document).ready(function () {
        $("#agregar").click(function () {
            agregar();
        });
    });
    
    var cont = 0;
    total = 0;
    subtotal = [];
    
    $("#guardar").hide();


    function agregar() {
        product_id = $("#product_id").val();
        provider_id = $("#provider_id").val();
        description = $("#description").val();
        producto = $("#product_id option:selected").text();
        quantity = $("#quantity").val();
        price = $("#price").val();

        console.log(producto);
        if (provider_id != "" && description != "" && product_id != "" && producto != "" && quantity > 0 && price != "") {
            subtotal[cont] = quantity * price;
            total = total + subtotal[cont];
            var fila = '<tr class="selected" id="fila'+cont+'"><td><button type="button" class="btn btn-danger btn-sm" onclick="eliminar('+cont+');"><i class="fa fa-times"></i></button></td> <td><input type="hidden" id="product_id[]" name="product_id[]" value="'+product_id+'">'+producto+'</td> <td> <input type="hidden" id="price[]" name="price[]" value="' + price + '"> <input class="form-control" type="number" id="price[]" value="' + price + '" disabled> </td>  <td> <input type="hidden" name="quantity[]" value="' + quantity + '"> <input class="form-control" type="number" value="' + quantity + '" disabled> </td> <td align="right">Q. ' + subtotal[cont] + ' </td></tr>';
            cont++;

         
            limpiar();
            totales();
            evaluar();
            $('#detalles').append(fila);
        } else {
            Swal.fire({
                type: 'error',
                text: 'Rellene todos los campos del detalle de la compras',
    
            })
        }
    }
    
    function limpiar() {
        $("#quantity").val("");
        $("#price").val("");
    }
    
    function totales() {
        $("#total").html("Q. " + total.toFixed(2));
        // total_impuesto = total * impuesto / 100;
         total_pagar = total;
       //$("#total_impuesto").html("PEN " + total_impuesto.toFixed(2));
        $("#total_pagar_html").html("Q " + total_pagar.toFixed(2));
        $("#total_pagar").val(total_pagar.toFixed(2));
    }
    
    function evaluar() {
        if (total > 0) {
            $("#guardar").show();
        } else {
            $("#guardar").hide();
        }
    }
    
    function eliminar(index) {
        total = total - subtotal[index];
        
        total_pagar_html = total ;
        $("#total").html("Q. " + total);
        //$("#total_impuesto").html("PEN" + total_impuesto);
        $("#total_pagar_html").html("Q" + total_pagar_html);
        $("#total_pagar").val(total_pagar_html.toFixed(2));
        $("#fila" + index).remove();
        evaluar();
    }
    
</script>
@endsection

resources/views/admin/purchase/index.blade.php
@extends('layouts.admin')

@section('title','Gestión de compras')
@section('styles')
<style type="text/css">
    .unstyled-button{
        border: none;
        padding: 0;
        background: none; 
    }
</style>
{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Compras
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">
                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item active" aria-current="page">Compras</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title"></h4>
                        <div class="btn-group">
                            <a href="{{route('purchases.create')}}" type="button" class="btn btn-info ">
                                <i class="fas fa-plus"></i> Registrar
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="purchase_listing" class="table tree">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Fecha</th>
                                    <th>Descripcion</th>
                                    <th>Total (Q)</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>                   
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach ($purchases as $purchase)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td>
                                    {{$purchase->purchase_date}}
                                    </td> 
                                    <td><a href="{{route('purchases.show',$purchase)}}">
                                        {{$purchase->description}}</a></td>
                                    <td>{{$purchase->total}}</td>
                                    @if($purchase->status == 'VALID')
                                    <td> <a href="{{route('change.status.purchases',$purchase)}}" title="Editar" class="jsgrid-button btn btn-success">
                                        Valido <i class="fas fa-check"></i>
                                    </a>
                                    </td>
                                    @else
                                    <td> <a href="{{route('change.status.purchases',$purchase)}}" title="Editar" class="jsgrid-button btn btn-danger">
                                        Invalido <i class="fas fa-times"></i>
                                    </a>
                                    </td>
                                    @endif
                                    <!-- <td>{{$purchase->status}}</td> -->

                                    <td style="">
                                        <!-- {!! Form::open(['route'=>['purchases.destroy',
                                            $purchase ], 'method'=>'DELETE']) !!} -->

                                        <!-- <a class="jsgrid-button jsgrid-edit-button" href="{{route('purchases.edit',$purchase)}}" title="Editar">
                                            <i class="far fa-edit"></i>
                                        </a>
                                       <button class="jsgrid-button jsgrid-delete-button unstyled-button" type="submit" title="Eliminar">
                                        <i class="far fa-trash-alt"></i>
                                        </button>  -->

                                        <!-- <td style="width: 20%;"> -->
                                        <a href="{{route('purchases.pdf', $purchase)}}" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="far fa-file-pdf"></i></a>
                                        
                                        <!-- <a href="#" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="fas fa-print"></i></a>  -->
                                        <a href="{{route('purchases.show',$purchase)}}" class="btn btn-outline-info"
                                        title="Ver detalles"
                                        ><i class="far fa-eye"></i></a>
                                        <!-- </td> -->
                                       <!-- {!! Form::close() !!} -->
                                    </td>
                                    
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                </div>
                <div class="card-footer text-muted">
                    {{$purchases->render()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

{!! Html::script('treegrid/js/jquery.treegrid.js') !!}
{!! Html::script('js/my_functions.js') !!}
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree').treegrid().treegrid('collapseAll');
    });
</script>
@endsection

resources/views/admin/purchase/pdf.blade.php
<!DOCTYPE>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Reporte de compra</title>
<style>
    body {
        /*position: relative;*/
        /*width: 16cm;  */
        /*height: 29.7cm; */
        /*margin: 0 auto; */
        /*color: #555555;*/
        /*background: #FFFFFF; */
        font-family: Arial, sans-serif;
        font-size: 14px;
        /*font-family: SourceSansPro;*/
    }


    #datos {
        float: left;
        margin-top: 0%;
        margin-left: 2%;
        margin-right: 2%;
        /*text-align: justify;*/
    }

    #encabezado {
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        font-size: 15px;
    }

    #fact {
        /*position: relative;*/
        float: right;
        margin-top: 2%;
        margin-left: 2%;
        margin-right: 2%;
        font-size: 20px;
        background: #33AFFF;
    }

    section {
        clear: left;
    }

    #cliente {
        text-align: left;
    }

    #faproveedor {
        width: 40%;
        border-collapse: collapse;
        border-spacing: 0;
        margin-bottom: 15px;
    }

    #fac,
    #fv,
    #fa {
        color: #FFFFFF;
        font-size: 15px;
    }

    #faproveedor thead {
        padding: 20px;
        background: #33AFFF;
        text-align: left;
        border-bottom: 1px solid #FFFFFF;
    }

    #faccomprador {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
        margin-bottom: 15px;
    }

    #faccomprador thead {
        padding: 20px;
        background: #33AFFF;
        text-align: center;
        border-bottom: 1px solid #FFFFFF;
    }

    #facproducto {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
        margin-bottom: 15px;
    }

    #facproducto thead {
        padding: 20px;
        background: #33AFFF;
        text-align: center;
        border-bottom: 1px solid #FFFFFF;
    }

</style>

<body>
  
    <header>
        {{--  <div id="logo">
            <img src="image/logo-lima.png" alt="" id="imagen">
        </div>  --}}
        <div>
            <table id="datos">
                <thead>
                    <tr>
                        <th id="">DATOS DEL PROVEEDOR</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>
                            <p id="proveedor">Nombre: {{$purchase->provider->name}}<br>
                                {{--  {{$purchase->provider->document_type}}-COMPRA: {{$purchase->provider->document_number}}<br>  --}}
                                Teléfono: {{$purchase->provider->numero}}<br>
                                Empresa: {{$purchase->provider->empresa}}<br>
                                Email: {{$purchase->provider->email}}</p>
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="fact">
                <p>Compra No. {{$purchase->id}}</p>
        </div>
    </header>
    <br> 
    <br>
    <section>
        <div>
            <table id="faccomprador" border="1">
                <thead>
                    <tr id="fv">
                        <th>USUARIO COMPRADOR</th>
                        <th>FECHA COMPRA</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td align="center">{{$purchase->user->name}}</td>
                        <td align="center">{{$purchase->purchase_date}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </section>
    <br>
    <section>
        <div>
            <table id="facproducto"  border="1">
                <thead>
                    <tr id="fa">
                        <th>No.</th>
                        <th>CATEGORIA</th>
                        <th>PRODUCTO</th>
                        <th>Cantidad<br>comprada</th>
                        <th>Precio de<br>compra</th>
                        <th>subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($purchaseDetails as $purchaseDetail)
                    <tr>
                        <td scope="row">{{$loop->iteration}}</td>
                        <td align="center">{{$purchaseDetail->product->category->name}}</td>
                        <td align="center">{{$purchaseDetail->product->name}}</td>
                        <td align="center">{{$purchaseDetail->quantity}}</td>
                        <td align="center">Q.  {{$purchaseDetail->price}}</td>
                        <td align="center">Q.  {{number_format($purchaseDetail->quantity*$purchaseDetail->price,2)}}</td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                 
                    <!-- <tr>
                        <th colspan="3">
                            <p align="right">SUBTOTAL:</p>
                        </th>
                        <td>
                            <p align="right">s/ {{number_format($subtotal,2)}}<p>
                        </td>
                    </tr> -->
                  
                    <!-- <tr>
                        <th colspan="3">
                            <p align="right">TOTAL IMPUESTO ({{$purchase->tax}}%):</p>
                        </th>
                        <td>
                            <p align="right">s/ {{number_format($subtotal*$purchase->tax/100,2)}}</p>
                        </td>
                    </tr> -->
                    <tr>
                        <th colspan="5">
                            <p align="right">TOTAL:</p>
                        </th>
                        <th><br>
                            <p align="center">Q. {{number_format($purchase->total,2)}}<p>
                        </th>
                    </tr>
                  
                </tfoot>
            </table>
        </div>
    </section>
    <br>
    <br>
    <footer>
        <!--puedes poner un mensaje aqui-->
        <div id="datos">
            <p id="encabezado">
                {{--  <b>{{$company->name}}</b><br>{{$company->description}}<br>Telefono:{{$company->telephone}}<br>Email:{{$company->email}}  --}} 
            </p>
        </div>
    </footer>
</body>

</html>