routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin', function () {
    return view('layouts/admin');
});

Route::get('/prueba', function () {
    return view('prueba');
});
//reportes
Route::get('sales/reports_day','ReportController@reports_days')->name('reports.day');
Route::get('sales/ reports_date', 'ReportController@reports_date')->name('reports.date');
Route::post('sales/report_results', 'ReportController@report_results')->name('report.results');


Route::get('search/productos','ProductController@search')->name('search.productos');

Route::resource('categories','CategoryController')->names('categories');
Route::resource('clients','ClientController')->names('clients');
Route::resource('products','ProductController')->names('products');
Route::resource('providers','ProviderController')->names('providers');
Route::resource('purchases','PurchaseController')->names('purchases');
Route::resource('sales' ,'SaleController')->names('sales');

Route::get('purchases/pdf/{purchase}', 'PurchaseController@pdf')->name('purchases.pdf');
Route::get('sales/pdf/{sale}', 'SaleController@pdf')->name('sales.pdf');
Route::get('productos/pdf', 'ProductController@pdf')->name('products.pdf');

Route::get('purchases/upload/{purchase}', 'PurchaseController@upload')->name('upload.purchases');


Route::get('change_status/products/{product}', 'ProductController@change_status')->name('change.status.products'); 
Route::get('change_status/purchases/{purchase}', 'PurchaseController@change_status')->name('change.status.purchases');
Route::get('change_status/sales/{sale}', 'SaleController@change_status')->name('change.status.sales');

Route::resource('user' ,'UserController')->names('users');
Route::resource('roles' ,'RoleController')->names('roles');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    protected $fillable = [
        'client_id',
        'user_id',
        'sale_date',
        'tax',
        'total',
        'status',
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }
    public function client(){
        return $this->belongsTo(Client::class);
    }
    public function saleDetails(){
        return $this->hasMany(saleDetail::class);
    }
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use App\Sale;
use App\Client;
use App\User;
use App\Product;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Request\Sale\StoreRequest;
use App\Http\Request\Sale\UpdateRequest;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Barryvdh\DomPDF\Facade\Pdf;
class SaleController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:sales.create')->only(['create','store']);
        $this->middleware('can:sales.index')->only(['index']);
        $this->middleware('can:sales.show')->only(['show']);
        
        $this->middleware('can:change.status.sales')->only(['change_status']);
        $this->middleware('can:sales.pdf')->only(['pdf']);
 

    }

    public function index(){
    $sales = Sale::paginate(5);
    return view('admin.sale.index', compact('sales'));
}
public function create()
{
    //$clients  = Client::role('Client')->get();
    //$products = Product::pos_products()->get();
    $clients = Client::get();
	$categories = Category::get();
    // $products = Product::get();
    $products = Product::orderBy('provider_id','asc')->orderBy('name','asc')->where('status','ACTIVO')->get();
    return view('admin.sale.create', compact('clients', 'products','categories'));
}
public function store(StoreRequest $request, Sale $sale)
{
    //$sale->my_store($request);
    $sale = Sale::create($request->all()+[
        'user_id'=>Auth::user()->id,
        'sale_date'=>Carbon::now('America/guatemala'),
    ]);
    foreach($request->product_id as $key=>$product){
        $results[] = array("product_id"=>$request->product_id[$key],
        "quantity" => $request->quantity[$key], "price"=>$request->price[$key],
        "discount"  => $request->discount[$key]);
    }
    $sale -> saleDetails()->createMany($results);
    return redirect()->route('sales.index')->with('toast_success', '¡Venta registrada con éxito!');
}
public function show(Sale $sale)
{
    $subtotal = 0 ;
    $saleDetails = $sale->saleDetails;
    foreach ($saleDetails as $saleDetail) {
        $subtotal += $saleDetail->quantity*$saleDetail->price
        -($saleDetail->quantity* $saleDetail->price)*$saleDetail->discount/100;
    }
    return view('admin.sale.show', compact('sale', 'saleDetails', 'subtotal'));
}
public function edit(Sale $sale)
{
    // $clients = Client::get();
    // return view('admin.sale.edit', compact('sale'));
}
public function update(UpdateRequest $request, Sale $sale)
{
    // $sale->update($request->all());
    // return redirect()->route('sales.index');
}
public function destroy(Sale $sale)
{
    // $sale->delete();
    // return redirect()->route('sales.index');
}
public function pdf(Sale $sale)
{
    $subtotal = 0 ;
    $ahorro = 0 ;

    $saleDetails = $sale->saleDetails;
    foreach ($saleDetails as $saleDetail) {
        $subtotal += $saleDetail->quantity*$saleDetail->price-$saleDetail->quantity* $saleDetail->price*$saleDetail->discount/100;
        $ahorro += $saleDetail->quantity* $saleDetail->price*$saleDetail->discount/100; 
       
    }
    $pdf = PDF::loadView('admin.sale.pdf', compact('sale', 'subtotal','ahorro', 'saleDetails'));
    return $pdf->download('Reporte_de_venta_'.$sale->id.'.pdf');
}

public function print(Sale $sale){
    try {
        $subtotal = 0 ;
        $saleDetails = $sale->saleDetails;
        foreach ($saleDetails as $saleDetail) {
            $subtotal += $saleDetail->quantity*$saleDetail->price-$saleDetail->quantity* $saleDetail->price*$saleDetail->discount/100;
        }  

        $printer_name = "TM20";
        $connector = new WindowsPrintConnector($printer_name);
        $printer = new Printer($connector);

        $printer->text("€ 9,95\n");

        $printer->cut();
        $printer->close();


        return redirect()->back();

    } catch (\Throwable $th) {
        return redirect()->back();
    }
}

public function change_status(Sale $sale)
{
    if ($sale->status == 'VALID') { 
        $sale->update(['status'=>'CANCELED']);
        return redirect()->back();
    } else {
        $sale->update(['status'=>'VALID']);
        return redirect()->back();
    } 
}
   
}

resources/views/admin/sale/_form.blade.php
<div class="form-group">
     <label for="client_ids">Cliente</label>
    <select class="form-control" name="client_id" id="client_id">
        <option value="">seleccione cliente</option>
        @foreach($clients as $client)
        <option value="{{$client->id}}">{{$client->name}} {{$client->apellido}}</option>
        @endforeach
    </select>
</div>
<!-- <div class="form-group">
    <label for="descriptions">Descripcion de compra</label>
    <input type="text"  class="form-control" name="description" id="description" 
        placeholder="Nombre" aria-describedby="helpId" >
</div> -->
 <div class="form-group">
     <label for="product_ids">Productos</label>
    <select class="form-control" name="product_id" id="product_id">
        <option value="">Seleccione Producto</option>
        @foreach($products as $product)
        <option value="{{$product->id}}_{{$product->stock}}_{{$product->price}}">prd- {{$product->category->name}} {{$product->name}}</option>
        @endforeach
    </select>
</div>
<div class="form-group">
    <label for="">Stock Actual</label>
    <input type="text" name="stock" id="stock" value="" class="form-control" disabled>
</div>
<div class="form-group">
    <label for="quantities">Cantidad Vendida</label>
    <input type="number"  class="form-control" name="quantity" id="quantity" 
        placeholder="cantidad" aria-describedby="helpId" >
</div>
<div class="form-group">
    <label for="prices">Precio</label>
    <input type="number"  class="form-control" name="price" id="price" 
        placeholder="" aria-describedby="helpId" disabled>
</div>
<div class="form-group">
    <label for="discounts">Porcentaje de Descuento</label>
    <input type="number"  class="form-control" name="discount" id="discount" 
        aria-describedby="helpId" value="0">
</div>

<div class="form-group">
    <button type="button" id="agregar" class="btn btn-primary float-right">Agregar Producto</button>
</div>

<div class="form-group">
    <h4 class="card-title">Detalles de venta</h4>
    <div class="table-responsive col-md-12">
         <table id="detalles" class="table table-striped">
            <thead>
                <tr>
                    <th>Eliminar</th>
                    <th>Producto</th>
                    <th>Precio Venta(Q)</th>
                    <th>Descuento%</th>
                    <th>Cantidad vendida</th>
                    <th>ahorro de cliente</th>
                    <th>Sub-total (Q)</th>
                </tr>
            </thead>
            <tfoot>  
                <!-- <tr>
                    <th colspan="6">
                        <p align="right" >TOTAL: </p>
                    </th>
                    <th>
                        <p align="right" ><span id="total">Q. 0.00</span></p>
                    </th>
                </tr> -->
                <tr id="">
                    <th colspan="6">
                        <p align="right" >Total a pagar: </p>
                    </th>
                    <th>
                        <p align="" ><span id="total_pagar_html">Q. 0.00</span>
                            <input type="hidden" name="total" id="total_pagar">
                        </p>
                    </th>
                </tr>
            </tfoot>
        </table>   
    </div>
</div>

resources/views/admin/sale/create.blade.php
@extends('layouts.admin')

@section('title','Registro de Ventas')
@section('styles')

{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Registro de Ventas
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">

                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item"><a href="{{route('sales.index')}}">Ventas</a></li>
                <li class="breadcrumb-item active" aria-current="page">registro de Ventas</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
            {!! Form::open(['route'=>'sales.store','method'=>'POST']) !!}
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title">Registro de Ventas</h4>          
                    </div>
                    
                    @include('admin.sale._form')                 

                </div>    
                <div class="card-footer text-muted">
                <button type="submit" id="guardar" class="btn btn-primary float-right">Registrar</button>
                    <a href="{{route('sales.index')}}" class="btn btn-light">Cancelar</a>
                </div>
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

{!! Html::script('melody/js/alerts.js') !!}
{!! Html::script('melody/js/avgrund.js') !!}

{!! Html::script('melody/js/bootstrap-select.min.js') !!}
{!! Html::script('melody/js/sweetalert2.all.min.js') !!}

{!! Html::script('melody/js/jquery.treegrid.js') !!}
{!! Html::script('melody/js/my_functions.js') !!}

<script>
    $(document).ready(function () {
        $("#agregar").click(function () {
            agregar();
        });
    });   

    var cont = 1;
    total = 0;
    subtotal = [];

    $("#guardar").hide();
    $("#product_id").change(mostrarValores);
  
    function mostrarValores(){
        datosProducto = document.getElementById('product_id').value.split('_');
        console.log(datosProducto);
        $("#price").val(datosProducto[2]);
        $("#stock").val(datosProducto[1]);
        
    }

    function agregar() {
        datosProducto = document.getElementById('product_id').value.split('_');
        product_id = datosProducto[0];
        producto = $("#product_id option:selected").text();
        quantity = $("#quantity").val();
        discount = $("#discount").val();
        price = $("#price").val();
        stock = $("#stock").val();    
        if (product_id != "" && quantity != "" && quantity > 0 && discount != "" && price != "") {
            console.log("errrorrr");
            if (parseInt(stock) >= parseInt(quantity)) {
                subtotal[cont] = (quantity * price) - (quantity * price * discount / 100);
                total = total + subtotal[cont];
                desc = quantity * price * discount / 100;
            var fila = '<tr class="selected" id="fila' + cont + '"><td><button type="button" class="btn btn-danger btn-sm" onclick="eliminar(' + cont + ');"><i class="fa fa-times fa-2x"></i></button></td> <td><input type="hidden" name="product_id[]" value="' + product_id + '">' + producto + '</td> <td> <input type="hidden" name="price[]" value="' + parseFloat(price).toFixed(2) + '"> <input class="form-control" type="number" value="' + parseFloat(price).toFixed(2) + '" disabled> </td> <td> <input type="hidden" name="discount[]" value="' + parseFloat(discount) + '"> <input class="form-control" type="number" value="' + parseFloat(discount) + '" disabled> </td> <td> <input type="hidden" name="quantity[]" value="' + quantity + '"> <input type="number" value="' + quantity + '" class="form-control" disabled> </td> <td> <input type="hidden" name="desc[]" value="' + parseFloat(desc).toFixed(2) + '"> <input type="number" value="' + parseFloat(desc).toFixed(2) + '" class="form-control" disabled> </td>  <td align="right">s/' + parseFloat(subtotal[cont]).toFixed(2) + '</td></tr>';

            cont++;    
            limpiar();
            totales();
            evaluar();
            $('#detalles').append(fila);
             } else {
            Swal.fire({
                type: 'error',
                text: 'Rellene todos los campos del detalle de la Ventas',
            });
            }
        }
    }
    
    function limpiar() {
        // $("#price").val("");
        $("#quantity").val("");
        $("#discount").val("0");
    }
    
    function totales() {
        $("#total").html("Q. " + total.toFixed(2));
        // total_impuesto = total * impuesto / 100;
         total_pagar = total;
       //$("#discount").html("Q " + total_impuesto.toFixed(2));
        $("#total_pagar_html").html("Q " + total_pagar.toFixed(2));
        $("#total_pagar").val(total_pagar.toFixed(2));
    }
    
    function evaluar() {
        if (total > 0) {
            $("#guardar").show();
        } else {
            $("#guardar").hide();
        }
    }
    
    function eliminar(index) {
        total = total - subtotal[index];
        total_pagar_html = total ;
        $("#total").html("Q. " + total);
        //$("#total_impuesto").html("PEN" + total_impuesto);
        $("#total_pagar_html").html("Q" + total_pagar_html);
        $("#total_pagar").val(total_pagar_html.toFixed(2));
        $("#fila" + index).remove();
        evaluar();
    }
    
</script>

@endsection

resources/views/admin/sale/index.blade.php
@extends('layouts.admin')

@section('title','Gestión de Ventas')
@section('styles')
<style type="text/css">
    .unstyled-button{
        border: none;
        padding: 0;
        background: none; 
    }
</style>
{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Ventas
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">
                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ventas</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title"></h4>
                        <div class="btn-group">
                            <a href="{{route('sales.create')}}" type="button" class="btn btn-info">
                                <i class="fas fa-plus"></i> Registrar
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="sale_listing" class="table tree">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Fecha</th>
                                    <th>Total</th>
                                    <th>Estado</th>
                                    <th style="width:150px">Acciones</th>                   
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach ($sales as $sale)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td>
                                    {{$sale->sale_date}}
                                    </td> 

                                    <td>{{$sale->total}}</td>
                                    @if($sale->status == 'VALID')
                                    <td> <a href="{{route('change.status.sales',$sale)}}" title="Editar" class="jsgrid-button btn btn-success">
                                        Valido <i class="fas fa-check"></i>
                                    </a>
                                    </td>
                                    @else
                                    <td> <a href="{{route('change.status.sales',$sale)}}" title="Editar" class="jsgrid-button btn btn-danger">
                                        Invalido <i class="fas fa-times"></i>
                                    </a>
                                    </td>
                                    @endif
                                    <!-- <td>{{$sale->status}}</td> -->
                                    <!-- <td style="width: 150px"> -->
                                        <!-- {!! Form::open(['route'=>['sales.destroy',
                                            $sale ], 'method'=>'DELETE']) !!} -->

                                        <!-- <a class="jsgrid-button jsgrid-edit-button" href="{{route('sales.edit',$sale)}}" title="Editar">
                                            <i class="far fa-edit"></i>
                                        </a>
                                       <button class="jsgrid-button jsgrid-delete-button unstyled-button" type="submit" title="Eliminar">
                                        <i class="far fa-trash-alt"></i>
                                        </button>  -->

                                        <td style="width: 20%;">
                                        <a href="{{route('sales.pdf',$sale)}}" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="far fa-file-pdf"></i></a>
                                        <!-- <a href="#" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="fas fa-print"></i></a> -->
                                        <a href="{{route('sales.show',$sale)}}" class="btn btn-outline-info"
                                        title="Ver detalles"
                                        ><i class="far fa-eye"></i></a>
                                        </td>
                                       <!-- {!! Form::close() !!} -->
                                    <!-- </td> -->
                                    
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                </div>
                <div class="card-footer text-muted">
                    {{$sales->render()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

{!! Html::script('treegrid/js/jquery.treegrid.js') !!}
{!! Html::script('js/my_functions.js') !!}
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree').treegrid().treegrid('collapseAll');
    });
</script>
@endsection

resources/views/admin/sale/show.blade.php
@extends('layouts.admin')
@section('title','Detalles de venta')
@section('styles')

@endsection
@section('create')

@endsection
@section('options')

@endsection
@section('preference')

@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Detalle de venta
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">
                <li class="breadcrumb-item"><a href="#">Panel administrador</a></li> 
                <li class="breadcrumb-item"><a href="{{route('sales.index')}}">Ventas</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{$sale->sale_date}}</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                <div class="form-group row">
                        <div class="col-md-4 text-center">
                            <label class="form-control-label"><strong>Cliente</strong></label>
                            <p><a href="{{route('clients.show', $sale->client)}}">{{$sale->client->name}}</a></p>
                        </div>
                        <div class="col-md-4 text-center">
                            <label class="form-control-label"><strong>Vendedor</strong></label>
                            <p>
                                <a href="#">{{$sale->user->name}}</a>
                            </p>
                        </div>
                        <div class="col-md-4 text-center">
                            <label class="form-control-label"><strong>Número Venta</strong></label>
                            <p>{{$sale->id}}</p>
                        </div>
                    </div>
                    <br /><br />
                    <div class="form-group">
                        <h4 class="card-title">Detalles de venta</h4>
                        <div class="table-responsive col-md-12">
                            <table id="saleDetails" class="table">
                                <thead>
                                    <tr>
                                        <th>Producto</th>
                                        <th>Precio Venta (Q)</th>
                                        <th>Descuento(Q)</th>
                                        <th>Cantidad</th>
                                        <th>SubTotal(Q)</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <!-- <tr>
                                        <th colspan="4">
                                            <p align="right">SUBTOTAL:</p>
                                        </th>
                                        <th>
                                            <p align="right">s/{{number_format($subtotal,2)}}</p>
                                        </th>
                                    </tr> -->                           
                                    <tr>
                                        <th colspan="4">
                                            <p align="right">TOTAL:</p>
                                        </th>
                                        <th>
                                            <p align="right">Q. {{number_format($sale->total,2)}}</p>
                                        </th>
                                    </tr>

                                </tfoot>
                                <tbody>
                                    @foreach($saleDetails as $saleDetail)
                                    <tr>
                                        <td>{{$saleDetail->product->name}}</td>
                                        <td>s/ {{$saleDetail->price}}</td>
                                        <td>{{$saleDetail->discount}} %</td>
                                        <td>{{$saleDetail->quantity}}</td>
                                        <td>s/{{number_format($saleDetail->quantity*$saleDetail->price - $saleDetail->quantity*$saleDetail->price*$saleDetail->discount/100,2)}}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
                <div class="card-footer text-muted">
                    <a href="{{route('sales.index')}}" class="btn btn-primary float-right">Regresar</a>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection
@section('scripts')
{!! Html::script('melody/js/profile-demo.js') !!}
{!! Html::script('melody/js/data-table.js') !!}
@endsection