routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin', function () {
    return view('layouts/admin');
});

Route::get('/prueba', function () {
    return view('prueba');
});
//reportes
Route::get('sales/reports_day','ReportController@reports_days')->name('reports.day');
Route::get('sales/ reports_date', 'ReportController@reports_date')->name('reports.date');
Route::post('sales/report_results', 'ReportController@report_results')->name('report.results');


Route::get('search/productos','ProductController@search')->name('search.productos');

Route::resource('categories','CategoryController')->names('categories');
Route::resource('clients','ClientController')->names('clients');
Route::resource('products','ProductController')->names('products');
Route::resource('providers','ProviderController')->names('providers');
Route::resource('purchases','PurchaseController')->names('purchases');
Route::resource('sales' ,'SaleController')->names('sales');

Route::get('purchases/pdf/{purchase}', 'PurchaseController@pdf')->name('purchases.pdf');
Route::get('sales/pdf/{sale}', 'SaleController@pdf')->name('sales.pdf');
Route::get('productos/pdf', 'ProductController@pdf')->name('products.pdf');

Route::get('purchases/upload/{purchase}', 'PurchaseController@upload')->name('upload.purchases');


Route::get('change_status/products/{product}', 'ProductController@change_status')->name('change.status.products'); 
Route::get('change_status/purchases/{purchase}', 'PurchaseController@change_status')->name('change.status.purchases');
Route::get('change_status/sales/{sale}', 'SaleController@change_status')->name('change.status.sales');

Route::resource('user' ,'UserController')->names('users');
Route::resource('roles' ,'RoleController')->names('roles');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Sale;
use Carbon\Carbon;
class ReportController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:reports.day')->only(['reports_days']);
        $this->middleware('can:reports.date')->only(['reports_date']);

    }

    public function reports_days(){
        $sales = Sale::WhereDate('sale_date', Carbon::today('America/guatemala'))->paginate(10);
        $total = $sales->sum('total');
        return view('admin.report.reports_day', compact('sales', 'total'));
    }
    public function reports_date(){
        $sales = Sale::whereDate('sale_date', Carbon::today('America/guatemala'))->paginate(10);
        $total = $sales->sum('total');
        return view('admin.report.reports_date', compact('sales', 'total'));

    }
    public function report_results(Request $request){
        $fi = $request->fecha_ini. ' 00:00:00';
        $ff = $request->fecha_fin. ' 23:59:59';
        $sales = Sale::whereBetween('sale_date', [$fi, $ff])->paginate(5);
        $total = $sales->sum('total');
        return view('admin.report.reports_date', compact('sales', 'total'));
    }
}

resources/views/admin/report/reports_date.blade.php
@extends('layouts.admin')

@section('title','Reporte por rango de fecha')
@section('styles')
<style type="text/css">
    .unstyled-button{
        border: none;
        padding: 0;
        background: none; 
    }
</style>
{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Reporte por rango de fecha
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">
                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item active" aria-current="page">Reporte de Ventas</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                              
                    </div>
                    {!! Form::open(['route'=>'report.results', 'method'=>'POST']) !!}
                    <div class="row ">
                    <div class="col-12 col-md-3">
                            <span>Fecha inicial</span>
                            <div class="form-group">
                                <input class="form-control" type="date" 
                                value="{{old('fecha_ini')}}" 
                                name="fecha_ini" id="fecha_ini">
                            </div>
                        </div>
                        <div class="col-12 col-md-3">
                            <span>Fecha final</span>
                            <div class="form-group">
                                <input class="form-control" type="date" 
                                value="{{old('fecha_fin')}}" 
                                name="fecha_fin" id="fecha_fin">
                            </div>
                        </div>
                        <div class="col-12 col-md-3 text-center mt-4">
                            <div class="form-group">
                               <button type="submit" class="btn btn-primary btn-sm">Consultar</button>
                            </div>
                        </div>
                        <div class="col-12 col-md-3 text-center">
                            <span>Total de ingresos: <b> </b></span>
                            <div class="form-group">
                                <strong>Q. {{$total}}</strong>
                            </div>
                        </div>    
                    </div>
                    {!! Form::close() !!}
                    <div class="table-responsive">
                        <table id="sale_listing" class="table tree">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Fecha</th>
                                    <th>Total</th>
                                    <th>Estado</th>
                                    <th style="width:150px">Acciones</th>                   
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach ($sales as $sale)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td>
                                    {{$sale->sale_date}}
                                    </td> 

                                    <td>{{$sale->total}}</td>
                                    <td>{{$sale->status}}</td>
                                    <!-- <td style="width: 150px"> -->
                                        <!-- {!! Form::open(['route'=>['sales.destroy',
                                            $sale ], 'method'=>'DELETE']) !!} -->

                                        <!-- <a class="jsgrid-button jsgrid-edit-button" href="{{route('sales.edit',$sale)}}" title="Editar">
                                            <i class="far fa-edit"></i>
                                        </a>
                                       <button class="jsgrid-button jsgrid-delete-button unstyled-button" type="submit" title="Eliminar">
                                        <i class="far fa-trash-alt"></i>
                                        </button>  -->

                                        <td style="width: 20%;">
                                        <a href="{{route('sales.pdf',$sale)}}" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="far fa-file-pdf"></i></a>
                                        <!-- <a href="#" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="fas fa-print"></i></a> -->
                                        <a href="{{route('sales.show',$sale)}}" class="btn btn-outline-info"
                                        title="Ver detalles"
                                        ><i class="far fa-eye"></i></a>
                                        </td>
                                       <!-- {!! Form::close() !!} -->
                                    <!-- </td> -->
                                    
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                </div>
                <div class="card-footer text-muted">
                    {{$sales->render()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

{!! Html::script('treegrid/js/jquery.treegrid.js') !!}
{!! Html::script('js/my_functions.js') !!}
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree').treegrid().treegrid('collapseAll');
    });
</script>
<script>
    window.onload = function(){
        var fecha = new Date(); //Fecha actual
        var mes = fecha.getMonth()+1; //obteniendo mes
        var dia = fecha.getDate(); //obteniendo dia
        var ano = fecha.getFullYear(); //obteniendo año
        if(dia<10)
          dia='0'+dia; //agrega cero si el menor de 10
        if(mes<10)
          mes='0'+mes //agrega cero si el menor de 10
        document.getElementById('fecha_fin').value=ano+"-"+mes+"-"+dia;
      }
</script>

@endsection

resources/views/admin/report/reports_day.blade.php
@extends('layouts.admin')

@section('title','Reporte de ventas')
@section('styles')
<style type="text/css">
    .unstyled-button{
        border: none;
        padding: 0;
        background: none; 
    }
</style>
{!! Html::style('treegrid/css/jquery.treegrid.css') !!}
@endsection
@section('options')
@endsection
@section('preference')
@endsection
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
            Reporte de Ventas
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-custom">
                <li class="breadcrumb-item"><a href="">Panel administrador</a></li>
                <li class="breadcrumb-item active" aria-current="page">Reporte de Ventas</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                              
                    </div>
                    <div class="row ">
                        <div class="col-12 col-md-4 text-center">
                            <span>Fecha de consulta: <b> </b></span>
                            <div class="form-group">
                                <strong>{{\Carbon\Carbon::now()->format('d/m/Y')}}</strong>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 text-center">
                            <span>Cantidad de registros: <b></b></span>
                            <div class="form-group">
                                <strong>{{$sales->count()}}</strong>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 text-center">
                            <span>Total de ingresos: <b> </b></span> 
                            <div class="form-group">
                                <strong>Q. {{$total}}</strong>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="sale_listing" class="table tree">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Fecha</th>
                                    <th>Total</th>
                                    <th>Estado</th>
                                    <th style="width:150px">Acciones</th>                   
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach ($sales as $sale)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td>
                                    {{$sale->sale_date}}
                                    </td> 

                                    <td>{{$sale->total}}</td>
                                    <td>{{$sale->status}}</td>
                                    <!-- <td style="width: 150px"> -->
                                        <!-- {!! Form::open(['route'=>['sales.destroy',
                                            $sale ], 'method'=>'DELETE']) !!} -->

                                        <!-- <a class="jsgrid-button jsgrid-edit-button" href="{{route('sales.edit',$sale)}}" title="Editar">
                                            <i class="far fa-edit"></i>
                                        </a>
                                       <button class="jsgrid-button jsgrid-delete-button unstyled-button" type="submit" title="Eliminar">
                                        <i class="far fa-trash-alt"></i>
                                        </button>  -->

                                        <td style="width: 20%;">
                                        <a href="{{route('sales.pdf',$sale)}}" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="far fa-file-pdf"></i></a>
                                        <!-- <a href="#" class="btn btn-outline-danger"
                                        title="Generar PDF"
                                        ><i class="fas fa-print"></i></a> -->
                                        <a href="{{route('sales.show',$sale)}}" class="btn btn-outline-info"
                                        title="Ver detalles"
                                        ><i class="far fa-eye"></i></a>
                                        </td>
                                       <!-- {!! Form::close() !!} -->
                                    <!-- </td> -->
                                    
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                </div>
                <div class="card-footer text-muted">
                    {{$sales->render()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

{!! Html::script('treegrid/js/jquery.treegrid.js') !!}
{!! Html::script('js/my_functions.js') !!}
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree').treegrid().treegrid('collapseAll');
    });
</script>
@endsection